### ISSUE TITLE
Some properties not shown under Properties

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/WikidataClassBrowser#28]
The property P580 (start time) is not to be found in the property browser. End time is also missing. Something seems to cause some properties to vanish. The properties correctly appear on property pages, showing that the relevant data is in the json file.

**Comment by mkroetzsch** [comment]
@guenthermi Any progress on this? This is currently blocking public announcement of the tool.

**Comment by guenthermi** [comment]
fixed by #34

**Comment by mkroetzsch** [comment]
Oh, I see. Is this fix future-safe? Or should the code maybe be modified to ignore the upper bound when it is the maximum that can be set? One could also determine the upper bound from the data, but then a good rounding approach would be needed.
