### ISSUE TITLE
Indicate query processing state

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/WikidataClassBrowser#32]
The query view should indicate when we are waiting for results by adding a spinner. It should also indicate when a query timed out or otherwise failed. Currently this happens only in some cases, but apparently not on all timeouts. In case of a timeout, the server may respond with a partial result list that is interrupted by a Java exception string.

**Comment by arsylum** [comment]
Spinner added in 0ed5b8c212738d38b2da7cdd84958baa97bfc839

Introduces dependency on [spin.js](http://fgnass.github.io/spin.js/) in `lib/spin.min.js`

**Comment by mkroetzsch** [comment]
The spinner is an example of a feature that would be useful for all components. It would be good to get a first version of the query branch merged at some point ...
