### ISSUE TITLE
browse view permanent link should store sort order

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/WikidataClassBrowser#35]
It seems that the currently selected sorting criterion is not stored in the permanent link.

**Comment by guenthermi** [comment]
Yes, this was not considered until now. It should work since #46.

**Comment by mkroetzsch** [comment]
Not sure this works as expected. The links now say things like

http://tools.wmflabs.org/sqid/#/browse?activepage=4&type=classes&sortclassinstances=fa fa-sort&sortclasssubclasses=fa fa-sort-asc

when I sort by subclasses. The entry for instances seems irrelevant. Also, the encoding in URL parameters is not so great. I would expect something like

http://tools.wmflabs.org/sqid/#/browse?activepage=4&type=classes&sort=subclasses&order=asc

This is readable and shorter. In general, it would be good to make the parameters short, esp. the very common ones ("page" could be "p"; and "type" could be "t" etc.). Doing this later is problematic since it might break existing links.
