### ISSUE TITLE
Do not use  uselang=en for Wikidata link with no lang

### ISSUE THREAD

**Issue by fnielsen** [Wikidata/WikidataClassBrowser#41]
If SQID has no lang parameter in URL, then link to Wikidata defaults to 'en'. It would be better if it defaulted to nothing, so the user's choice on Wikidata is maintained.

**Comment by mkroetzsch** [comment]
Thanks, good point. Fixed in master and online (may require hard reload in the browser to see the change).

**Comment by fnielsen** [comment]
I can confirm that is works at my side now. Thanks.
