### ISSUE TITLE
Property links incorrect

### ISSUE THREAD

**Issue by athalhammer** [Wikidata/WikidataClassBrowser#44]
Hi,

The link to the respective Wikidata page is incorrect for property pages (e.g. on http://tools.wmflabs.org/sqid/#/view?id=P106). The click on *P106* (top) leads to 

    https://www.wikidata.org/wiki/P106

instead of

    https://www.wikidata.org/wiki/Property:P106

This happens also for the "Wikidata page" link. This could be fixed by linking to the entity page (for properties and entities - i.e. using  https://www.wikidata.org/entity/ instead of https://www.wikidata.org/wiki/).

Andreas

**Comment by mkroetzsch** [comment]
Thanks, fixed in master and online. We do not use the entity link since we want to use the "uselang" parameter in some cases, so we insert "Property:" now where appropriate.

**Comment by mkroetzsch** [comment]
P.S. A Shift+Reload might be needed to see the changes in the browser.
