### ISSUE TITLE
Split messages into files

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/WikidataClassBrowser#61]
Angular Translate supports loading messages asynchronously from separate files. This would be much better than having messages inline in one file as it is now. To use this functionality, only the registration/setup code for angular translate needs to be changed, but it may be necessary to use another dependency (the file loading feature may not be part of the library as we use it).

**Comment by arsylum** [comment]
this is now implemented in the [refactor branch](https://github.com/Wikidata/WikidataClassBrowser/tree/refactor)

<sup>(though for yet to be clarified reasons it is a bit peculiar to work with in context of the requirejs environment)</sup>
