### ISSUE TITLE
Show references

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/WikidataClassBrowser#69]
The View view should also show the references for each statement. The information should be hidden/collapsed by default.

**Comment by mkroetzsch** [comment]
Implemented for most statements, and live online. Incoming links do not show references yet (this would need more work still), but you can always click on the entity they come from to see them. Moreover, the inline classes/superclasses shown at the top don't have references, since I don't know where to put them there.

**Comment by egonw** [comment]
Super, well done! The account is very prominent, maybe too distracting in the current form.

**Comment by mkroetzsch** [comment]
What do you mean with "the account"? Do you mean the buttons to show the references? Any suggestions for making them less prominent (I cannot really make them any smaller or shorter when trying to keep them readable).

**Comment by egonw** [comment]
Sorry... yes, I meant the button to show the references.

What about removing the bookmark icon, and just leave the number?

**Comment by mkroetzsch** [comment]
There might be more "additional things" besides references that one could unfold there in the future. It could therefore make sense to replace the whole button with a simple ">" symbol that turns into "v" when expanded. Then the numbers would not be visible, but it would be maximally discrete.

**Comment by mkroetzsch** [comment]
I updated the code and online app now to do this. There is a loss of information (no ref counts) but it is much more readable. It is also future-ready in that we can add more (more controls, more displays, etc.) to the collapsible area of each statement. Maybe one could have options to display additional information later on, so that power users can see, e.g., reference counts for each statement without clicking it first.
